### ISSUE TITLE
NPM mdi-svg

### ISSUE THREAD

**Issue by Templarian** [conundrumer/mdi-svg#1]
Starting with `v2+` we'll be publishing SVG files for third party libraries.

Just noticed you're using this name `mdi-svg` already. Is there anyway you could transfer it to me?

https://github.com/Templarian/MaterialDesign-SVG

If you can, the steps are:

https://docs.npmjs.com/cli/owner

```
npm owner add templarian
```

**Comment by conundrumer** [comment]
@Templarian added you as an owner!

**Comment by Templarian** [comment]
Thanks very much. Glad you like the project. This will help us open the library up for more 3rd party integration going forward (following similar structured/tested version releases).

😄

**Comment by Templarian** [comment]
Done, switched over everything. Will tweet tomorrow a thank you, do you have twitter?

(Releasing the large 2.0.xx release).

**Comment by conundrumer** [comment]
Thanks for managing this whole thing! Looking forward to more integration.
[I'm on twitter](https://twitter.com/d_e_lu)
